import 'package:flutter/material.dart';
import '../models/catalog.dart';
import '../services/app_state.dart';
import '../theme.dart';
import 'order_tracking.dart';
class CartScreen extends StatefulWidget{const CartScreen({super.key});@override State<CartScreen> createState()=>_CartScreenState();}
class _CartScreenState extends State<CartScreen>{final s=AppState.instance;final address=TextEditingController(text:'ميت غمر - شارع التحرير');@override Widget build(BuildContext context){return Scaffold(appBar:AppBar(title:const Text('سلة الطلب',style:TextStyle(fontWeight:FontWeight.w900))),body:s.cart.isEmpty?const Center(child:Text('السلة فاضية — اختار وجبة الأول')):ListView(padding:const EdgeInsets.all(18),children:[...s.cart.map((line)=>_Line(line:line,onChanged:()=>setState((){}))),const SizedBox(height:10),TextField(controller:address,decoration:const InputDecoration(labelText:'عنوان التوصيل',prefixIcon:Icon(Icons.location_on_outlined))),const SizedBox(height:14),_Row('الإجمالي قبل التوصيل','${s.subtotal.toStringAsFixed(0)} ج.م'),_Row('التوصيل','${s.deliveryFee.toStringAsFixed(0)} ج.م'),const Divider(height:28),_Row('الإجمالي','${s.total.toStringAsFixed(0)} ج.م',bold:true),const SizedBox(height:18),SizedBox(height:55,child:FilledButton.icon(onPressed:(){final r=s.allRestaurants.firstWhere((r)=>r.menu.any((m)=>s.cart.any((c)=>c.item.id==m.id)),orElse:()=>s.allRestaurants.first);s.placeOrder(r,address.text);setState((){});Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>OrderTracking(order:s.activeOrder!)));},icon:const Icon(Icons.check_circle_outline),label:const Text('تأكيد الطلب والدفع عند الاستلام')))]);}}
class _Line extends StatelessWidget{final CartLine line;final VoidCallback onChanged;const _Line({required this.line,required this.onChanged});@override Widget build(BuildContext context){final s=AppState.instance;return Card(child:Padding(padding:const EdgeInsets.all(12),child:Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(line.item.name,style:const TextStyle(fontWeight:FontWeight.w900)),Text('${line.item.price.toStringAsFixed(0)} ج.م')]),),IconButton(onPressed:(){s.remove(line.item);onChanged();},icon:const Icon(Icons.remove_circle_outline)),Text('${line.quantity}',style:const TextStyle(fontWeight:FontWeight.w900)),IconButton(onPressed:(){s.add(line.item);onChanged();},icon:const Icon(Icons.add_circle_outline,color:NovaTheme.primary))]));}}
class _Row extends StatelessWidget{final String a,b;final bool bold;const _Row(this.a,this.b,{this.bold=false});@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(children:[Expanded(child:Text(a,style:TextStyle(fontWeight:bold?FontWeight.w900:FontWeight.w500))),Text(b,style:TextStyle(fontWeight:bold?FontWeight.w900:FontWeight.w600,fontSize:bold?18:14))]));}
