import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import '../models/order.dart';
import '../services/app_state.dart';
import '../theme.dart';
import '../widgets/nova_header.dart';
import '../widgets/map_panel.dart';
import 'order_tracking.dart';

class CourierHome extends StatefulWidget { const CourierHome({super.key}); @override State<CourierHome> createState()=>_CourierHomeState(); }
class _CourierHomeState extends State<CourierHome>{final s=AppState.instance;bool online=true;final orders=const [
  DeliveryOrder(id:'NOVA-2041',customerName:'أحمد',restaurantName:'Nova Burger',customerAddress:'ميت غمر - شارع التحرير',restaurantAddress:'شارع الجمهورية',customerLat:30.7160,customerLng:31.2590,restaurantLat:30.7070,restaurantLng:31.2550,items:[OrderItem(name:'Nova Beef Burger',qty:1,price:145),OrderItem(name:'Loaded Fries',qty:1,price:55)],total:215,status:OrderStatus.pending),
  DeliveryOrder(id:'NOVA-2042',customerName:'سارة',restaurantName:'Pizza Nova',customerAddress:'ميت غمر - شارع المدارس',restaurantAddress:'شارع الجيش',customerLat:30.7200,customerLng:31.2500,restaurantLat:30.7140,restaurantLng:31.2450,items:[OrderItem(name:'Chicken Ranch',qty:1,price:220)],total:238,status:OrderStatus.pending),
];
@override Widget build(BuildContext context){return Scaffold(appBar:AppBar(title:const Text('لوحة المندوب',style:TextStyle(fontWeight:FontWeight.w900)),actions:[Switch(value:online,onChanged:(v)=>setState(()=>online=v))]),body:ListView(padding:const EdgeInsets.fromLTRB(18,8,18,30),children:[NovaHeader(title:online?'أنت متاح الآن 🟢':'أنت غير متاح',subtitle:'أول مندوب يقبل الطلب يتم تعيينه له'),const SizedBox(height:16),Row(children:[_Stat('طلبات اليوم','12'),_Stat('دخل اليوم','780 ج'),_Stat('التقييم','4.9 ★')]),const SizedBox(height:18),if(!online)const Card(child:Padding(padding:EdgeInsets.all(18),child:Text('أنت غير متاح لاستقبال الطلبات الجديدة.'))),if(online)...orders.map((o)=>_Offer(order:o))]);}}
class _Stat extends StatelessWidget{final String a,b;const _Stat(this.a,this.b);@override Widget build(BuildContext context)=>Expanded(child:Card(child:Padding(padding:const EdgeInsets.symmetric(vertical:15),child:Column(children:[Text(b,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w900)),const SizedBox(height:5),Text(a,style:TextStyle(color:Colors.grey.shade600,fontSize:12))]))));}
class _Offer extends StatefulWidget{final DeliveryOrder order;const _Offer({required this.order});@override State<_Offer> createState()=>_OfferState();}
class _OfferState extends State<_Offer>{bool busy=false;bool accepted=false;Future<void> accept()async{setState(()=>busy=true);await Future.delayed(const Duration(milliseconds:500));if(!mounted)return;setState((){busy=false;accepted=true;});AppState.instance.activeOrder=widget.order.copyWith(status:OrderStatus.accepted,driverName:'مندوب نوفا');AppState.instance.notifyListeners();}
@override Widget build(BuildContext context){final o=widget.order;return Card(margin:const EdgeInsets.only(bottom:14),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.notifications_active_rounded,color:NovaTheme.accent),const SizedBox(width:8),Expanded(child:Text(o.restaurantName,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w900))),Text('${o.total.toStringAsFixed(0)} ج.م',style:const TextStyle(fontWeight:FontWeight.w900))]),const SizedBox(height:10),Text('العميل: ${o.customerName}'),Text('الاستلام: ${o.restaurantAddress}'),Text('التسليم: ${o.customerAddress}'),const SizedBox(height:10),MapPanel(restaurant:LatLng(o.restaurantLat,o.restaurantLng),customer:LatLng(o.customerLat,o.customerLng),height:175),const SizedBox(height:10),Row(children:[Expanded(child:OutlinedButton(onPressed:busy||accepted?null:()=>ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('تم تجاهل الطلب'))),child:const Text('رفض'))),const SizedBox(width:10),Expanded(child:FilledButton(onPressed:busy||accepted?null:accept,child:busy?const SizedBox(width:20,height:20,child:CircularProgressIndicator(strokeWidth:2)):Text(accepted?'تم القبول ✓':'قبول الطلب')))]),if(accepted)Padding(padding:const EdgeInsets.only(top:10),child:FilledButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>OrderTracking(order:o.copyWith(status:OrderStatus.accepted,driverName:'مندوب نوفا')))),icon:const Icon(Icons.navigation_rounded),label:const Text('فتح رحلة التوصيل'))]));}}
