import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

const ink = Color(0xFF111322);
const violet = Color(0xFF7357FF);
const coral = Color(0xFFFF6B57);
const bg = Color(0xFFF7F7FB);
const muted = Color(0xFF777B8A);

void main() => runApp(const NovaApp());

class NovaApp extends StatelessWidget {
  const NovaApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false,
    title: 'Nova Delivery',
    theme: ThemeData(useMaterial3: true, scaffoldBackgroundColor: bg, fontFamily: 'Roboto', colorScheme: ColorScheme.fromSeed(seedColor: violet)),
    home: const Shell(),
  );
}

class Restaurant {
  final String name, category, eta, rating, image, offer;
  final int fee;
  const Restaurant(this.name,this.category,this.eta,this.rating,this.image,this.offer,this.fee);
}
const restaurants = [
  Restaurant('Burger Lab','برجر • أمريكي','25-35 دقيقة','4.9','🍔','خصم 35%',25),
  Restaurant('Pasta House','إيطالي • باستا','30-40 دقيقة','4.8','🍝','توصيل مجاني',0),
  Restaurant('Sushi Wave','سوشي • ياباني','35-45 دقيقة','4.7','🍣','خصم 20%',30),
  Restaurant('Grill District','مشويات • شرقي','20-30 دقيقة','4.9','🥩','وجبة + مشروب',20),
];

class CartItem { final String name; final int price; int qty; CartItem(this.name,this.price,[this.qty=1]); }

class AppState extends ChangeNotifier {
  final List<CartItem> cart=[]; final Set<String> favs={}; bool dark=false;
  int get subtotal=>cart.fold(0,(s,i)=>s+i.price*i.qty);
  int get delivery=>subtotal==0?0:(subtotal>=250?0:25);
  int get total=>subtotal+delivery;
  void add(String n,int p){ final i=cart.where((x)=>x.name==n); if(i.isEmpty) cart.add(CartItem(n,p)); else i.first.qty++; notifyListeners(); }
  void dec(String n){ final i=cart.where((x)=>x.name==n).firstOrNull; if(i==null)return; i.qty--; if(i.qty<=0)cart.remove(i); notifyListeners(); }
  void fav(String n){ favs.contains(n)?favs.remove(n):favs.add(n); notifyListeners(); }
}
final appState=AppState();

class Shell extends StatefulWidget{const Shell({super.key});State<Shell> createState()=>_ShellState();}
class _ShellState extends State<Shell>{int tab=0;
 final pages=const [Home(), Explore(), Orders(), Profile()];
 @override Widget build(BuildContext c)=>AnimatedBuilder(animation:appState,builder:(_,__)=>Scaffold(body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),height:74,destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'الرئيسية'),NavigationDestination(icon:Icon(Icons.explore_outlined),selectedIcon:Icon(Icons.explore),label:'استكشف'),NavigationDestination(icon:Icon(Icons.receipt_long_outlined),selectedIcon:Icon(Icons.receipt_long),label:'طلباتي'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'حسابي')])));}
}

class Home extends StatelessWidget{const Home({super.key});
 @override Widget build(BuildContext c)=>SafeArea(child:CustomScrollView(slivers:[
  SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(20,18,20,0),child:Row(children:[Container(width:44,height:44,decoration:BoxDecoration(color:ink,borderRadius:BorderRadius.circular(15)),child:const Icon(Icons.local_shipping_rounded,color:Colors.white)),const SizedBox(width:12),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('التوصيل إلى',style:TextStyle(color:muted,fontSize:12)),Row(children:[Icon(Icons.location_on_rounded,color:violet,size:16),Text(' مدينة نصر، القاهرة',style:TextStyle(fontWeight:FontWeight.w800))])])),IconButton(onPressed:()=>c.push(MaterialPageRoute(builder:(_)=>const Notifications())),icon:const Icon(Icons.notifications_none_rounded))]))),
  SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.all(20),child:Container(height:190,padding:const EdgeInsets.all(22),decoration:BoxDecoration(gradient:const LinearGradient(colors:[ink,Color(0xFF30295C)]),borderRadius:BorderRadius.circular(30)),child:Stack(children:[const Positioned(right:0,top:0,child:Icon(Icons.bolt_rounded,size:95,color:Color(0x227357FF))),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:6),decoration:BoxDecoration(color:coral,borderRadius:BorderRadius.circular(20)),child:const Text('عرض اليوم',style:TextStyle(color:Colors.white,fontWeight:FontWeight.bold,fontSize:12))),const Spacer(),const Text('خصم يصل إلى',style:TextStyle(color:Colors.white70,fontSize:14)),const Text('40%',style:TextStyle(color:Colors.white,fontSize:42,fontWeight:FontWeight.w900,height:1)),const Text('على أول طلب • استخدم NOVA40',style:TextStyle(color:Colors.white70)),const Spacer(),FilledButton(onPressed:()=>c.push(MaterialPageRoute(builder:(_)=>const Explore())),style:FilledButton.styleFrom(backgroundColor:Colors.white,foregroundColor:ink),child:const Text('اطلب الآن'))])]))),
  const SliverToBoxAdapter(child:SectionTitle('تصفح حسب النوع')),
  SliverToBoxAdapter(child:SizedBox(height:105,child:ListView.separated(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:20),itemCount:6,separatorBuilder:(_,__)=>const SizedBox(width:12),itemBuilder:(_,i){final a=[['🍔','برجر'],['🍕','بيتزا'],['🍣','سوشي'],['🍰','حلويات'],['🥩','مشويات'],['🥗','صحي']][i];return Container(width:82,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.04),blurRadius:15)]),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(a[0],style:const TextStyle(fontSize:28)),const SizedBox(height:5),Text(a[1],style:const TextStyle(fontWeight:FontWeight.w700,fontSize:12))]));} })),
  const SliverToBoxAdapter(child:SectionTitle('مطاعم قريبة منك')),
  SliverList(delegate:SliverChildBuilderDelegate((c,i)=>RestaurantCard(r:restaurants[i]),childCount:restaurants.length)),
  const SliverToBoxAdapter(child:SizedBox(height:30)),
 ]));}
}
class SectionTitle extends StatelessWidget{final String t;const SectionTitle(this.t,{super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.fromLTRB(20,8,20,14),child:Row(children:[Text(t,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900)),const Spacer(),Text('عرض الكل',style:TextStyle(color:violet,fontWeight:FontWeight.bold))]));}
class RestaurantCard extends StatelessWidget{final Restaurant r;const RestaurantCard({required this.r,super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.fromLTRB(20,0,20,14),child:InkWell(borderRadius:BorderRadius.circular(25),onTap:()=>c.push(MaterialPageRoute(builder:(_)=>RestaurantPage(r:r))),child:Container(padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(25),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.035),blurRadius:18,offset:const Offset(0,7))]),child:Row(children:[Container(width:92,height:92,decoration:BoxDecoration(color:const Color(0xFFF0EEFF),borderRadius:BorderRadius.circular(20)),child:Center(child:Text(r.image,style:const TextStyle(fontSize:48)))),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(r.name,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:16))),Container(padding:const EdgeInsets.symmetric(horizontal:7,vertical:4),decoration:BoxDecoration(color:const Color(0xFFFFF0EC),borderRadius:BorderRadius.circular(9)),child:Text(r.offer,style:const TextStyle(color:coral,fontSize:10,fontWeight:FontWeight.bold)))]),const SizedBox(height:7),Text(r.category,style:const TextStyle(color:muted,fontSize:12)),const SizedBox(height:9),Row(children:[const Icon(Icons.star_rounded,color:Color(0xFFFFB300),size:17),Text(' ${r.rating}',style:const TextStyle(fontWeight:FontWeight.bold)),const Text('  •  ',style:TextStyle(color:muted)),const Icon(Icons.schedule_rounded,color:muted,size:15),Text(' ${r.eta}',style:const TextStyle(color:muted,fontSize:11))])]))]))));}

class RestaurantPage extends StatelessWidget{final Restaurant r;const RestaurantPage({required this.r,super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(r.name),actions:[IconButton(onPressed:()=>appState.fav(r.name),icon:Icon(appState.favs.contains(r.name)?Icons.favorite:Icons.favorite_border,color:coral))]),body:Column(children:[Container(margin:const EdgeInsets.fromLTRB(20,8,20,15),height:150,decoration:BoxDecoration(color:const Color(0xFFEDEAFF),borderRadius:BorderRadius.circular(28)),child:Center(child:Text(r.image,style:const TextStyle(fontSize:80))),),Padding(padding:const EdgeInsets.symmetric(horizontal:20),child:Row(children:[Text(r.category,style:const TextStyle(color:muted)),const Spacer(),Text('⭐ ${r.rating}',style:const TextStyle(fontWeight:FontWeight.bold)),const SizedBox(width:10),Text(r.eta,style:const TextStyle(color:muted,fontSize:12))])),const SizedBox(height:18),const TabBar(tabs:[Tab(text:'الأكثر طلبًا'),Tab(text:'برجر'),Tab(text:'مشروبات')]),Expanded(child:ListView(padding:const EdgeInsets.all(20),children:[FoodTile('Nova Classic Burger','برجر لحم، جبنة، صوص نوفا',145,'🍔'),FoodTile('Crispy Chicken','دجاج مقرمش وصوص خاص',125,'🍗'),FoodTile('Loaded Fries','بطاطس، جبنة وصوص',75,'🍟'),FoodTile('Fresh Cola','مشروب غازي بارد',35,'🥤')]))]),bottomNavigationBar:AnimatedBuilder(animation:appState,builder:(_,__)=>appState.cart.isEmpty?const SizedBox.shrink():Padding(padding:const EdgeInsets.all(14),child:FilledButton.icon(onPressed:()=>c.push(MaterialPageRoute(builder:(_)=>const CartPage())),icon:const Icon(Icons.shopping_bag_outlined),label:Text('السلة • ${appState.total} ج.م')))));}
class FoodTile extends StatelessWidget{final String n,d,e;final int p;FoodTile(this.n,this.d,this.p,this.e,{super.key});@override Widget build(BuildContext c)=>Container(margin:const EdgeInsets.only(bottom:12),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22)),child:Row(children:[Container(width:70,height:70,decoration:BoxDecoration(color:const Color(0xFFF3F1FF),borderRadius:BorderRadius.circular(18)),child:Center(child:Text(e,style:const TextStyle(fontSize:35)))),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(n,style:const TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:4),Text(d,style:const TextStyle(color:muted,fontSize:11)),const SizedBox(height:8),Text('$p ج.م',style:const TextStyle(fontWeight:FontWeight.w900,color:violet))])),IconButton(onPressed:(){appState.add(n,p);ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('تمت الإضافة إلى السلة')));},style:IconButton.styleFrom(backgroundColor:ink,foregroundColor:Colors.white),icon:const Icon(Icons.add))]));}

class CartPage extends StatelessWidget{const CartPage({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('السلة')),body:AnimatedBuilder(animation:appState,builder:(_,__)=>appState.cart.isEmpty?const Center(child:Text('السلة فارغة')):Column(children:[Expanded(child:ListView(padding:const EdgeInsets.all(20),children:appState.cart.map((i)=>Container(margin:const EdgeInsets.only(bottom:12),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:Row(children:[Expanded(child:Text(i.name,style:const TextStyle(fontWeight:FontWeight.bold))),IconButton(onPressed:()=>appState.dec(i.name),icon:const Icon(Icons.remove_circle_outline)),Text('${i.qty}',style:const TextStyle(fontWeight:FontWeight.bold)),IconButton(onPressed:()=>appState.add(i.name,i.price),icon:const Icon(Icons.add_circle_outline)),Text('${i.price*i.qty}'))]).toList())),Padding(padding:const EdgeInsets.all(20),child:Column(children:[SummaryRow('المجموع الفرعي',appState.subtotal),SummaryRow('التوصيل',appState.delivery),const Divider(),SummaryRow('الإجمالي',appState.total,bold:true),const SizedBox(height:12),SizedBox(width:double.infinity,height:54,child:FilledButton(onPressed:()=>c.push(MaterialPageRoute(builder:(_)=>const Checkout())),child:const Text('متابعة الدفع')))]))])));}
class SummaryRow extends StatelessWidget{final String t;final int v;final bool bold;const SummaryRow(this.t,this.v,{this.bold=false,super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(children:[Text(t,style:TextStyle(fontWeight:bold?FontWeight.w900:FontWeight.normal)),const Spacer(),Text('$v ج.م',style:TextStyle(fontWeight:bold?FontWeight.w900:FontWeight.bold))]));}

class Checkout extends StatelessWidget{const Checkout({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('تأكيد الطلب')),body:ListView(padding:const EdgeInsets.all(20),children:[const Text('عنوان التوصيل',style:TextStyle(fontWeight:FontWeight.w900,fontSize:18)),const SizedBox(height:10),Card(child:ListTile(leading:const Icon(Icons.location_on,color:violet),title:const Text('مدينة نصر، القاهرة'),subtitle:const Text('شارع عباس العقاد • مبنى 18'),trailing:const Icon(Icons.edit_outlined))),const SizedBox(height:22),const Text('طريقة الدفع',style:TextStyle(fontWeight:FontWeight.w900,fontSize:18)),const SizedBox(height:10),Card(child:Column(children:[RadioListTile(value:1,groupValue:1,onChanged:(_){},title:const Text('الدفع عند الاستلام'),secondary:const Icon(Icons.payments_outlined)),RadioListTile(value:2,groupValue:1,onChanged:(_){},title:const Text('بطاقة بنكية — جاهزة للربط'),secondary:const Icon(Icons.credit_card_outlined))])),const SizedBox(height:22),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(children:[SummaryRow('الإجمالي',appState.total,bold:true),const SizedBox(height:14),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:(){Navigator.push(c,MaterialPageRoute(builder:(_)=>const TrackingPage()));},child:const Text('تأكيد الطلب')))])))]));}

class TrackingPage extends StatefulWidget{const TrackingPage({super.key});State<TrackingPage>createState()=>_TrackingState();}
class _TrackingState extends State<TrackingPage>{GoogleMapController? map; LatLng driver=const LatLng(30.056,31.347), customer=const LatLng(30.061,31.333);@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('تتبع طلبك'),actions:[IconButton(onPressed:(){map?.animateCamera(CameraUpdate.newLatLngBounds(LatLngBounds(southwest:LatLng(math.min(driver.latitude,customer.latitude)-.002,math.min(driver.longitude,customer.longitude)-.002),northeast:LatLng(math.max(driver.latitude,customer.latitude)+.002,math.max(driver.longitude,customer.longitude)+.002)),60));},icon:const Icon(Icons.my_location))]),body:Stack(children:[GoogleMap(initialCameraPosition:CameraPosition(target:customer,zoom:14.5),onMapCreated:(x)=>map=x,markers:{Marker(markerId:const MarkerId('driver'),position:driver,infoWindow:const InfoWindow(title:'المندوب')),Marker(markerId:const MarkerId('customer'),position:customer,infoWindow:const InfoWindow(title:'موقعك'))},polylines:{Polyline(polylineId:const PolylineId('route'),points:[driver,LatLng(30.057,31.343),LatLng(30.059,31.339),customer],width:6,color:violet)}}),Positioned(bottom:0,left:0,right:0,child:Container(padding:const EdgeInsets.fromLTRB(20,18,20,25),decoration:const BoxDecoration(color:Colors.white,borderRadius:BorderRadius.vertical(top:Radius.circular(30))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Row(children:[CircleAvatar(backgroundColor:Color(0xFFEDEAFF),child:Icon(Icons.two_wheeler,color:violet)),SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('محمد • المندوب',style:TextStyle(fontWeight:FontWeight.w900)),Text('الدراجة في الطريق إليك',style:TextStyle(color:muted,fontSize:12))])),Text('8 دقائق',style:TextStyle(color:violet,fontWeight:FontWeight.w900))]),const SizedBox(height:18),ClipRRect(borderRadius:BorderRadius.circular(10),child:LinearProgressIndicator(value:.72,minHeight:7)),const SizedBox(height:14),const Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('تم تأكيد الطلب'),Text('قيد التوصيل'),Text('تم التسليم')])])))]));}

class Explore extends StatelessWidget{const Explore({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('استكشف'),bottom:PreferredSize(preferredSize:const Size.fromHeight(64),child:Padding(padding:const EdgeInsets.fromLTRB(20,0,20,12),child:TextField(decoration:InputDecoration(prefixIcon:const Icon(Icons.search),hintText:'ابحث عن مطعم أو وجبة',filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:BorderSide.none))))),body:ListView(padding:const EdgeInsets.only(top:15),children:restaurants.map((r)=>RestaurantCard(r:r)).toList()));}
class Orders extends StatelessWidget{const Orders({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('طلباتي')),body:ListView(padding:const EdgeInsets.all(20),children:[Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:ink,borderRadius:BorderRadius.circular(25)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Row(children:[Icon(Icons.local_shipping,color:Colors.white),SizedBox(width:8),Text('طلب قيد التوصيل',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900))]),const SizedBox(height:12),const Text('#NV-2841 • Burger Lab',style:TextStyle(color:Colors.white70)),const SizedBox(height:15),FilledButton(onPressed:()=>c.push(MaterialPageRoute(builder:(_)=>const TrackingPage())),style:FilledButton.styleFrom(backgroundColor:Colors.white,foregroundColor:ink),child:const Text('تتبع الطلب'))]),const SizedBox(height:14),Card(child:ListTile(leading:const Text('🍝',style:TextStyle(fontSize:30)),title:const Text('Pasta House'),subtitle:const Text('تم التسليم • أمس'),trailing:Text('245 ج.م',style:const TextStyle(fontWeight:FontWeight.bold)))]) ;}}
class Profile extends StatelessWidget{const Profile({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('حسابي')),body:ListView(padding:const EdgeInsets.all(20),children:[Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:const LinearGradient(colors:[ink,Color(0xFF332B68)]),borderRadius:BorderRadius.circular(28)),child:const Row(children:[CircleAvatar(radius:30,backgroundColor:Color(0x337357FF),child:Icon(Icons.person,color:Colors.white,size:30)),SizedBox(width:14),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('أهلاً بك في Nova',style:TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.w900)),Text('عضوية Nova Plus',style:TextStyle(color:Colors.white70))])])),const SizedBox(height:18),...['العناوين المحفوظة','طرق الدفع','المفضلة','الكوبونات والعروض','الإشعارات','الإعدادات','مركز المساعدة'].map((x)=>Card(child:ListTile(title:Text(x),trailing:const Icon(Icons.chevron_left))))]));}}
class Notifications extends StatelessWidget{const Notifications({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('الإشعارات')),body:ListView(padding:const EdgeInsets.all(20),children:const [Card(child:ListTile(leading:Icon(Icons.local_shipping,color:violet),title:Text('مندوبك في الطريق'),subtitle:Text('محمد استلم طلبك وسيصل خلال 8 دقائق.'))),Card(child:ListTile(leading:Icon(Icons.local_offer,color:coral),title:Text('خصم 40%'),subtitle:Text('استخدم كود NOVA40 على طلبك القادم.')))]);}}
