import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import '../models/order.dart';
import '../services/app_state.dart';
import '../theme.dart';
import '../widgets/map_panel.dart';
class OrderTracking extends StatefulWidget{final DeliveryOrder order;const OrderTracking({super.key,required this.order});@override State<OrderTracking> createState()=>_OrderTrackingState();}
class _OrderTrackingState extends State<OrderTracking>{final s=AppState.instance;OrderStatus status=OrderStatus.pending;@override void initState(){super.initState();status=s.activeOrder?.status??widget.order.status;s.addListener(_sync);}@override void dispose(){s.removeListener(_sync);super.dispose();}void _sync(){if(mounted)setState(()=>status=s.activeOrder?.status??status);}
void next(){final n=switch(status){OrderStatus.pending=>OrderStatus.accepted,OrderStatus.accepted=>OrderStatus.pickedUp,OrderStatus.pickedUp=>OrderStatus.onTheWay,OrderStatus.onTheWay=>OrderStatus.delivered,OrderStatus.delivered=>OrderStatus.delivered,OrderStatus.cancelled=>OrderStatus.cancelled};s.setStatus(n,driver:'محمد');setState(()=>status=n);}
@override Widget build(BuildContext context){final o=s.activeOrder??widget.order;return Scaffold(appBar:AppBar(title:const Text('تتبع الطلب',style:TextStyle(fontWeight:FontWeight.w900))),body:ListView(padding:const EdgeInsets.fromLTRB(16,4,16,30),children:[MapPanel(restaurant:LatLng(o.restaurantLat,o.restaurantLng),customer:LatLng(o.customerLat,o.customerLng),driver:status.index>=OrderStatus.accepted.index?const LatLng(30.7115,31.2570):null,height:350),const SizedBox(height:16),Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const CircleAvatar(backgroundColor:Color(0x126C4CF1),child:Icon(Icons.restaurant_rounded,color:NovaTheme.primary)),const SizedBox(width:10),Expanded(child:Text(o.restaurantName,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:18))),Text('#${o.id}')]),const Divider(height:26),...o.items.map((i)=>Padding(padding:const EdgeInsets.only(bottom:7),child:Row(children:[Text('${i.qty}×'),const SizedBox(width:8),Expanded(child:Text(i.name)),Text('${i.price.toStringAsFixed(0)} ج.م')]))),const Divider(),Row(children:[const Expanded(child:Text('الإجمالي',style:TextStyle(fontWeight:FontWeight.w800))),Text('${o.total.toStringAsFixed(0)} ج.م',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:18))])])),),const SizedBox(height:16),const Text('حالة الطلب',style:TextStyle(fontSize:19,fontWeight:FontWeight.w900)),const SizedBox(height:8),..._steps.map((x)=>_Step(title:x.$1,icon:x.$2,active:_activeFor(x.$3))),const SizedBox(height:8),if(status!=OrderStatus.delivered)SizedBox(height:52,child:FilledButton(onPressed:next,child:Text(_nextLabel(status)))),if(status==OrderStatus.delivered)const Card(child:Padding(padding:EdgeInsets.all(18),child:Text('تم تسليم الطلب بنجاح 🎉',style:TextStyle(fontWeight:FontWeight.w900))))]);}
bool _activeFor(OrderStatus x)=>status.index>=x.index;String _nextLabel(OrderStatus x)=>switch(x){OrderStatus.pending=>'محاكاة: قبول الطلب',OrderStatus.accepted=>'محاكاة: استلام من المطعم',OrderStatus.pickedUp=>'محاكاة: في الطريق للعميل',OrderStatus.onTheWay=>'محاكاة: تم التسليم',_=>'متابعة'};
}
final _steps=[('تم استلام الطلب',Icons.receipt_long_rounded,OrderStatus.pending),('تم قبول الطلب',Icons.check_circle_outline,OrderStatus.accepted),('المندوب استلم الطلب',Icons.restaurant_rounded,OrderStatus.pickedUp),('المندوب في الطريق',Icons.two_wheeler_rounded,OrderStatus.onTheWay),('تم التسليم',Icons.home_rounded,OrderStatus.delivered)];
class _Step extends StatelessWidget{final String title;final IconData icon;final bool active;const _Step({required this.title,required this.icon,required this.active});@override Widget build(BuildContext context)=>ListTile(contentPadding:EdgeInsets.zero,leading:CircleAvatar(backgroundColor:active?NovaTheme.primary:Colors.grey.shade200,child:Icon(icon,color:active?Colors.white:Colors.grey)),title:Text(title,style:TextStyle(fontWeight:active?FontWeight.w800:FontWeight.w500)),trailing:active?const Icon(Icons.check_circle_rounded,color:NovaTheme.secondary):null);}
